/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devchina_lame_DevchinaActivity */

#ifndef _Included_com_devchina_lame_DevchinaActivity
#define _Included_com_devchina_lame_DevchinaActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_devchina_lame_DevchinaActivity
 * Method:    getLameVesion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_devchina_lame_DevchinaActivity_getLameVesion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
