/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_base64test_JniTest */

#ifndef _Included_com_zhuabjie_client_utils_EncryptUtils
#define _Included_com_zhuabjie_client_utils_EncryptUtils
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_zhubajie_client_utils_EncryptUtils_encrypt(
		JNIEnv *, jobject, jbyteArray);

JNIEXPORT jstring JNICALL Java_com_zhubajie_client_utils_EncryptUtils_encrypturl(
		JNIEnv *, jobject, jbyteArray,jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
